networks:
  graython-net:
    driver: bridge
services:
  graython-web:
    image: graython-website:latest
    container_name: graython-website
    volumes:
      # 【需修改】
      # 将冒号(:)前的部分改成你运行 docker 的设备的某个路径，不要修改冒号后面的内容。
      # 如果是windows环境，可以使用/c/mnt/green/blossom/img/来指定磁盘
      # blossom 上传图片的存储路径，不要修改冒号后面的内容。
      - /Users/pengjunlee/Downloads/img/:/home/bl/
      # website要管理的资源根路径，不要修改冒号后面的内容。
      - /Users/pengjunlee/Downloads/:/app/data/
    environment:
      # Blossom MySQL数据库配置
      SPRING_DATASOURCE_URL: jdbc:mysql://graython-mysql:3306/blossom?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&allowMultiQueries=true&useSSL=false&&serverTimezone=GMT%2B8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      # Website MySQL数据库配置
      WEBSITE_DATASOURCE_URL: jdbc:mysql://graython-mysql:3306/website?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&allowMultiQueries=true&useSSL=false&&serverTimezone=GMT%2B8
      WEBSITE_DATASOURCE_USERNAME: root
      WEBSITE_DATASOURCE_PASSWORD: 123456
    ports:
      # Blossom 对外暴露的9999端口（不要更改）
      - "9999:9999"
      # Website 对外暴露的8081端口,不要修改冒号后面的内容。
      - "7777:8081"
    networks:
      - graython-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/sys/alive"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: always
    depends_on:
      graython-mysql:
        condition: service_healthy
  graython-mysql:
    image: mysql:8.0.31
    container_name: graython-mysql
    restart: on-failure:3
    volumes:
      # 由于需要创建两个数据库，使用初始化脚本处理
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      # 【需修改】将冒号(:)前的部分改成你运行 docker 的设备的某个路径，不要修改冒号后面的内容。
      - /Users/pengjunlee/Downloads/mysql/data:/var/lib/mysql
      - /Users/pengjunlee/Downloads/mysql/log:/var/log/mysql
      - /Users/pengjunlee/Downloads/mysql/mysql-files/log:/var/lib/mysql-files
    environment:
      # 数据库密码，与下面健康检测脚本保持一致
      MYSQL_ROOT_PASSWORD: 123456
      LANG: C.UTF-8
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    networks:
      - graython-net
    healthcheck:
      # 【可选修改】如果修改了上方的数据库密码「MYSQL_ROOT_PASSWORD」，下方的 -p 后的密码也要修改 
      test: ["CMD", "mysqladmin", "-uroot", "-p123456", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 3s
      retries: 12
