# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫ profile配置 ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
website:
  resource:
    # 要管理的资源根目录
    root: /app/data/
    # 每日限制流量，单位M
    limit-size: 102400
  aspose:
    # Aspose 文档转换密钥配置
    app-id:
    app-secret:
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫ bingo 框架配置 ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
bingo:
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫ helper ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  helper:
    enables: caffeine,dynamic_db
  log-sql: true
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫ dynamic datasource ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  db:
    default:
      name: website
    website:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${WEBSITE_DATASOURCE_URL}
      username: ${WEBSITE_DATASOURCE_USERNAME}
      password: ${WEBSITE_DATASOURCE_PASSWORD}
    blossom:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}